### ISSUE TITLE
Guitar Ui

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [tanmoy27112000/flutter_UI_design_hactoberfest#104]
I want to add an attractive Guitar UI

Like these and much more 

![Guitar UI](https://github.com/tanmoy27112000/flutter_UI_design_hactoberfest/assets/127650446/fb60ec38-da21-411c-8207-e01b805d2633)

Please assign this , I am interested to contribute my self in hacktoberfest _23 : )

**Comment by tanmoy27112000** [comment]
assigned

**Comment by Bharath-KumarReddy** [comment]
I had just resolved this issue and I made a PR #108 once please check and merge it _hacktoberfest_23 : )
