### ISSUE TITLE
Twitch Clone UI

### ISSUE THREAD

**Issue by Chandrakant0110** [tanmoy27112000/flutter_UI_design_hactoberfest#109]
Hey Tanmoy! Can you please assign me with this issue?

Actually, I was planning to make a Twitch Clone and for it I thought let's start it from beginning to end.
I will try to make it full-stack by adding some features like 
* Landing Page
* Login/SignUp
* Dashboard
Also, I will try to make it full stack by adding some -
* Authentication
* Screensharing
* Selecting Thumbnail
* Going Live
* Joining LiveStream
* Switching Camera etc.

Pov: Contributing to this repo for the 2nd yr! :)

**Comment by tanmoy27112000** [comment]
Here you go
