### ISSUE TITLE
Allan_Voice_assistant , Chatgpt along with Image generation

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [tanmoy27112000/flutter_UI_design_hactoberfest#113]
Allan_Voice_assistant Is an app build using Flutter and using OpenAI   API ;

It can speek to you and you ask any questions  like of chatgpt and also 

!!!!  You can ask and type to get a random image of your own imaginations for example 

A man coding in laptop on jupyter

can you assign this to me , I am interested to contribute myself in _hacktoberfest_23 : )

**Comment by tanmoy27112000** [comment]
Go ahead

**Comment by Bharath-KumarReddy** [comment]
Hey I resolved this issue and I made a PR #127   on the commit message of   **"a virtual assistant _jarvis_friday"**

once please go through it and merge it _hacktoberfest_23 : )
