### ISSUE TITLE
Crypto app ui design with data fetching from api

### ISSUE THREAD

**Issue by Ankush-Paul-02** [tanmoy27112000/flutter_UI_design_hactoberfest#121]

**Comment by tanmoy27112000** [comment]
Assigned to you @Ankush-Paul-02

**Comment by Ankush-Paul-02** [comment]
I'm creating the new pr, because the previous one I gave commit message to all folders

**Comment by Ankush-Paul-02** [comment]
Should I create a new issue for the new pr?

**Comment by Ankush-Paul-02** [comment]
I've created the pr with my actual folder not with my ref. Sir please check it.
