### ISSUE TITLE
Simple Login Flow UI using flutter

### ISSUE THREAD

**Issue by Shashank0271** [tanmoy27112000/flutter_UI_design_hactoberfest#17]
A minimal login page made in flutter and is suited for beginners who are just starting out. Please assign this issue to me

**Comment by tanmoy27112000** [comment]
@Shashank0271 you can start working

**Comment by Shashank0271** [comment]
it's going to be a single page, not a whole UI bundle. Is that accepted ?

**Comment by tanmoy27112000** [comment]
If you are creating login ui make sure you have signup and forget password ui as well

**Comment by Chandrakant0110** [comment]
I want to make animated UI & for it.
Can you Please assign this issue to me.

**Comment by Chandrakant0110** [comment]
if @Shashank0271 is not working on the issue. Then please assign it to me as I have already made the UI.

**Comment by Chandrakant0110** [comment]
@tanmoy27112000  Sir I've completed the task.
Actually, I'm facing some difficulties during push & pull request.
Can you please guide me with it?
