### ISSUE TITLE
House Estate App UI

### ISSUE THREAD

**Issue by KYKY62** [tanmoy27112000/flutter_UI_design_hactoberfest#20]
Hello! I want to work on this issue. I will create House Estate App UI using flutter.

**Comment by tanmoy27112000** [comment]
@KYKY62 you can start working

**Comment by KYKY62** [comment]
i am just create to be single-page (discover Page) , Is that accepted @tanmoy27112000 ?

**Comment by KYKY62** [comment]
Assigned me again please

**Comment by tanmoy27112000** [comment]
@KYKY62 are you creating multipage ui?

**Comment by piyushkumar12111111** [comment]
Assign this to me

**Comment by tanmoy27112000** [comment]
@piyushkumar12111111  you can start working

**Comment by piyushkumar12111111** [comment]
Work done Please check

**Comment by piyushkumar12111111** [comment]
I am doing it again
