### ISSUE TITLE
Banking App UI

### ISSUE THREAD

**Issue by devkishor8007** [tanmoy27112000/flutter_UI_design_hactoberfest#46]
On the hacktoberfest2022, Can I do this?
![4090353](https://user-images.githubusercontent.com/73419211/195069477-258ebe2f-cc36-4870-8a1c-c25b1f76c526.jpg)

source: https://www.freepik.com/free-vector/banking-app-interface-screens_9153722.htm#page=3&query=mobile%20app%20template&position=1&from_view=keyword

**Comment by tanmoy27112000** [comment]
Sure you can start working

**Comment by Ramubethi** [comment]
Assign me please @tanmoy27112000

**Comment by devkishor8007** [comment]
@tanmoy27112000 hello there!
please have a look https://github.com/tanmoy27112000/flutter_UI_design_hactoberfest/pull/92
Thank you
