### ISSUE TITLE
Complete Functioning Calculator App

### ISSUE THREAD

**Issue by Harshith1263** [tanmoy27112000/flutter_UI_design_hactoberfest#51]
I Would Like to Make a Calculator App.
That is of Beautiful UI Involving Neon Effects and also Implement Both Dark and Light Modes.
And also Completely Functional !!
Can U Please Assign this to me, Sir...

**Comment by tanmoy27112000** [comment]
you can start working !!

**Comment by Harshith1263** [comment]
Ok, Sir Thank you!!

**Comment by GitArya27** [comment]
I would like to work on this issue as well. can u please assign this issue to me .

**Comment by Harshith1263** [comment]
Sir, Now I'm Done With The Work!
And I've created a PR Sir 
I Feel It Is a Worthy Contribution Sir
If U Feel The Same
Please Merge It, Sir !!!

**Comment by tanmoy27112000** [comment]
Sure I will review it @Harshith1263 and @GitArya27 create a new issue and start working

**Comment by Harshith1263** [comment]
Thank You, Sir !!
