### ISSUE TITLE
Netflix App frontend-design

### ISSUE THREAD

**Issue by randhirshaw** [tanmoy27112000/flutter_UI_design_hactoberfest#6]

**Comment by tanmoy27112000** [comment]
@randhirshaw you can start working on it

**Comment by randhirshaw** [comment]
> @randhirshaw you can start working on it

Yeah, I started working on it!!, Is there any issue if I work on netflix ui using flutter?

**Comment by tanmoy27112000** [comment]
@randhirshaw  sure
