### ISSUE TITLE
Add our own projects with custom UI

### ISSUE THREAD

**Issue by shatanikmahanty** [tanmoy27112000/flutter_UI_design_hactoberfest#8]
@tanmoy27112000 is it possible to add our own projects that are not a clone of an existing app on play store/app store

**Comment by tanmoy27112000** [comment]
@shatanikmahanty  yes sure

**Comment by tanmoy27112000** [comment]
you just create a issue with the specific name of the ui and make the PR according to that

**Comment by AbhishekTiwari23** [comment]
@tanmoy27112000, I Want to add a basic tic tac toe game. Please give me a chance

**Comment by tanmoy27112000** [comment]
@AbhishekTiwari23  sure create a ticket and start working

**Comment by JeetDalal** [comment]
@tanmoy27112000 I would like to add Hangman game . Please give me a chance

**Comment by tanmoy27112000** [comment]
@JeetDalal please create a issue and you can start working

**Comment by JeetDalal** [comment]
Hi @tanmoy27112000 , I would like to work on creating Tic-Tac-Toe game , could you assign me this task.

**Comment by tanmoy27112000** [comment]
@JeetDalal create a ticket and start working I will assign it

**Comment by JeetDalal** [comment]
Hi @tanmoy27112000 , I would like to work on creating Gmail ui , please assign me this task

**Comment by tanmoy27112000** [comment]
@JeetDalal  done

**Comment by Anu-Mushkan** [comment]
I would like to build the UI of a Laundry App, please assign me !

**Comment by tanmoy27112000** [comment]
@Anu-Mushkan  you can create a ticket and start working

**Comment by dhairyajain29** [comment]
I would like to work on creating attractive login page and sign-in page , Its ui will be amazing. could you assign me this task? @shatanikmahanty @tanmoy27112000

**Comment by Nitin-Singh18** [comment]
@tanmoy27112000, can i add whatsApp UI ?
